ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "24.3.0"
    hooks:
      - id: black-jupyter

  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.16.0"
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==23.*]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "v4.0.0-alpha.8"
  #   hooks:
  #     - id: prettier
  #       types_or: [markdown, html, css, scss, javascript]
  #       args: [--prose-wrap=always]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.4"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
        exclude: ^data/rucio_utils.py|^src/HH4b/corrections/(data|makePUReWeightJSON.py)

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.6.1"
  #   hooks:
  #     - id: mypy
  #       files: src|tests
  #       args: []
  #       additional_dependencies:
  #         - pytest

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.6"
    hooks:
      - id: codespell
        types_or: [python, rst, markdown]
        args: ["--ignore-words", ".codespell-whitelist.txt"]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.10.0.1"
    hooks:
      - id: shellcheck
        exclude: .*templ.sh

  # - repo: local
  #   hooks:
  #     - id: disallow-caps
  #       name: Disallow improper capitalization
  #       language: pygrep
  #       entry: PyBind|Numpy|Cmake|CCache|Github|PyTest
  #       exclude: .pre-commit-config.yaml

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.16
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.1
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-readthedocs
